### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'token'

### ISSUE THREAD

**Issue by ingsme** [openSUSE/cepces#40]
Certificate requests fail with the following error:

```
2024-05-22 15:49:06,402 cepces.certmonger.operation.Submit<0x735f7d9dd690>:DEBUG:Result is: None
2024-05-22 15:49:06,403 __main__:ERROR:Traceback (most recent call last):
  File "/usr/local/libexec/certmonger/cepces-submit", line 72, in main
    result = operation()
  File "/usr/local/lib/python3.10/dist-packages/cepces-0.3.9-py3.10.egg/cepces/certmonger/operation.py", line 125, in __call__
    if result.token:
AttributeError: 'NoneType' object has no attribute 'token'
```

/etc/cepces/cepces.conf
```
[global]
server=server
type=Policy
auth=Kerberos
endpoint=https://${server}/ADPolicyProvider_CEP_${auth}/service.svc/CEP
cas=/etc/ssl/certs/
poll_interval=3600
openssl_seclevel=1
[kerberos]
keytab=/etc/krb5.keytab
realm=REALM
ccache=True
principals=
  ${SHORTNAME}$$
  host/${SHORTNAME}$$
  host/${fqdn}$$
  #${shortname}$$
enctypes=
  aes128-cts-hmac-sha1-96
  aes256-cts-hmac-sha1-96
delegate=True
[certificate]
certfile = "/path/to/cert.crt"
keyfile = "/path/to/key.crl"
```

OS: Ubuntu 22.04
Python 3.10.12

**Comment by ingsme** [comment]
We are using sssd + AD. The machines are joining AD and receive kerberos keytab. 

exerpt from sssd.conf:
```
[domain/KRBDOMAIN]
ad_domain = realm
krb5_realm = REALM
realmd_tags = manages-system joined-with-adcli
cache_credentials = True
# enumerate = True
id_provider = ad
krb5_store_password_if_offline = True
ldap_id_mapping = False
use_fully_qualified_names = False
fallback_homedir = /home/%u
access_provider = ad
```
klist -k
```
Keytab name: FILE:/etc/krb5.keytab
KVNO Principal
---- --------------------------------------------------------------------------
   5 MACHINE$@REALM
   5 MACHINE$@REALM
   5 MACHINE$@REALM
   5 NFS/MACHINE@REALM
   5 NFS/MACHINE@REALM
   5 NFS/MACHINE@REALM
   5 NFS/fqdn@REALM
   5 NFS/fqdn@REALM
   5 NFS/fqdn@REALM
   5 host/MACHINE@REALM
   5 host/MACHINE@REALM
   5 host/MACHINE@REALM
   5 host/fqdn@REALM
   5 host/fqdn@REALM
   5 host/fqdn@REALM
   5 RestrictedKrbHost/MACHINE@REALM
   5 RestrictedKrbHost/MACHINE@REALM
   5 RestrictedKrbHost/MACHINE@REALM
   5 RestrictedKrbHost/fqdn@REALM
   5 RestrictedKrbHost/fqdn@REALM
   5 RestrictedKrbHost/fqdn@REALM
```
cecpes.conf
```
[global]
server=server
type=Policy
auth=Kerberos
endpoint=https://${server}/ADPolicyProvider_CEP_${auth}/service.svc/CEP
cas=/etc/ssl/certs/
poll_interval=3600
openssl_seclevel=1
[kerberos]
keytab=/etc/krb5.keytab
realm=REALM
ccache=True
principals=
  ${SHORTNAME}$$
  host/${SHORTNAME}
  host/${fqdn}
  #${shortname}$$
enctypes=
  aes128-cts-hmac-sha1-96
  aes256-cts-hmac-sha1-96
delegate=True
[certificate]
certfile = "//path/to/root CA.crt"
keyfile = "/path/to/root CA.crl"
```

Full log:
[cepceslog.log](https://github.com/openSUSE/cepces/files/15416136/cepceslog.log)

**Comment by kbsx32** [comment]
Hi, @ingsme , may I ask you how have you solved the problem? I faced with the same issue like you.

**Comment by ingsme** [comment]
@kbsx32, Ubuntu has started to package this as `python3-cepces` so I use that rather than trying to package it myself.
