### ISSUE TITLE
list index out of range - ForestTrust

### ISSUE THREAD

**Issue by retogobat** [openSUSE/cepces#8]
Hi,

We tried to implement CEPCES in a multi Forest setup, where the cert requestor is located in domain A and the CEP/CES Server in domain B.

For windows clients, everythin is working fine. When setting up CEPCES on Linux, we get:

```
2022-03-21 10:46:30,270 cepces.certmonger.operation.FetchRoots<0x7f95246490>:DEBUG:Initializing cepces.certmonger.operation.FetchRoots<0x7f95246490>.
2022-03-21 10:46:30,278 __main__:ERROR:Traceback (most recent call last):
  File "/usr/local/libexec/certmonger/cepces-submit", line 69, in main
    result = operation()
  File "/usr/local/lib/python3.9/dist-packages/cepces-0.3.4-py3.9.egg/cepces/certmonger/operation.py", line 254, in __call__
    certs = list(self._service.certificate_chain or [])
  File "/usr/local/lib/python3.9/dist-packages/cepces-0.3.4-py3.9.egg/cepces/core.py", line 159, in certificate_chain
    data = self._policies.cas[index].certificate
  File "/usr/local/lib/python3.9/dist-packages/cepces-0.3.4-py3.9.egg/cepces/xml/binding.py", line 269, in __getitem__
    return self._list[key]
IndexError: list index out of range
```

When we join the cert requestor to the same domain as the CEP/CES Server, everything works fine.

certmonger version 0.79.13
sssd version 2.4.1

Regards

**Comment by raimiansch** [comment]
Hello!
I want to use cepces on RHEL7/CentOS 7. I have the same error message like in this issue. Is there any solution available for this bug now?

2023-03-16 08:46:06,252 __main__:ERROR:Traceback (most recent call last):
  File "/usr/libexec/certmonger/cepces-submit", line 80, in main
    result = operation()
  File "/usr/local/lib/python3.6/site-packages/cepces-0.3.7-py3.6.egg/cepces/certmonger/operation.py", line 254, in __call__
    certs = list(self._service.certificate_chain or [])
  File "/usr/local/lib/python3.6/site-packages/cepces-0.3.7-py3.6.egg/cepces/core.py", line 159, in certificate_chain
    data = self._policies.cas[index].certificate
  File "/usr/local/lib/python3.6/site-packages/cepces-0.3.7-py3.6.egg/cepces/xml/binding.py", line 269, in __getitem__
    return self._list[key]


I have installed following:
atsl-armt02 ~ # rpm -qa | grep -i cep
cepces-0.3.6-1.el7.noarch
python36-cepces-0.3.6-1.el7.noarch
cepces-selinux-0.3.6-1.el7.noarch
cepces-certmonger-0.3.6-1.el7.noarch

Thx for every help.
BR
Rainer
